number = set()
print(type(number))
n = input("Enter the number ")
number.add(int(n))

n = input("Enter the number ")
number.add(int(n))
n = input("Enter the number ")
number.add(int(n))
n = input("Enter the number ")
number.add(int(n))
n = input("Enter the number ")
number.add(int(n))
n = input("Enter the number ")
number.add(int(n))
n = input("Enter the number ")
number.add(int(n))
n = input("Enter the number ")
number.add(int(n))
print (number)
